server:
  port: 1440

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/svc_flight
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson