curl 'https://www.tui.pl/api/www/search/offers' \
  -H 'authority: www.tui.pl' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: pl-PL,pl;q=0.9' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'cookie: airports=""; destinations=""; jud="MQ7GDgj4aRKcBLtHmy+zzP7DGsn0ehQrockoO5CQ7mIq3iTsZhd0s7FkM7JYEus3hLnC5FWyBPXkLAftDdOX9LvHiOQV78hHDd6eH+4mePP8jjUhUnUvXbpksbzk/dwfmU3UGxDLDmTf2XAOh6YicrPhk1Rut5TFTQi4MxHObhCRnTJTBT42D3JKFukXvvflOhTX6tlNRUoFbHl+ylJ4XKQn4HiA1S4L8sXKZWVpUEp8F1cerOcledK0LE+nK9BpvC8mJRh+dWFpWTyHnX+pTKg9xS2MsK4ErqOmUCFENq4DOM2p3sPGWUJcDOR6DM9J/SFjUFjDWxgCTWHA+TAVWxbrSoOPo1K+NAQdGrelgIqFgERqgpa3t4n7u2x+R2cJzFqA5djoUv4cLsK9VSFJ+8rVDhYqGDQdS/2GFhi0c+7d3xwM9efhNNzuUr0DutrORNkljUv3HrCrVlDjfBkMhxPzBjkSViAY7Pz9Rb7/pCgUKalqnIJLXAGjYxzEc04mTV6+WyrOVygU/RJxvajjGMbODpPRXJcVVjWAyYXPeirUGelNVAgg9sPGIt+EHWrUZtuSYqOWyZ6cFF+Gg1SWgSXIPBuCqS6Hlt3Gy7RlwBVZQfhF0FVYW1tHgsEnOJEkMy3YwH3aZ5GWFVb4+o74XXWS014Pg1uSJ74MknCXM5E="; tuiLastSearch=26488bdf-f9d1-4674-af7b-9594d11d6778; travelType="WS"; adultsCount=2; childrenCount=0; JSESSIONID=web12~C363441878103DBC269DBEEF16C3CEBF' \
  -H 'origin: https://www.tui.pl' \
  -H 'referer: https://www.tui.pl/wypoczynek/wyniki-wyszukiwania-samolot?q=%3Aprice%3AbyPlane%3AT%3AdF%3A6%3AdT%3A8%3ActAdult%3A2%3ActChild%3A0%3AminHotelCategory%3AdefaultHotelCategory%3AtripAdvisorRating%3AdefaultTripAdvisorRating%3Abeach_distance%3AdefaultBeachDistance%3AtripType%3AWS&fullPrice=false' \
  -H 'sec-ch-ua: "Not_A Brand";v="99", "Brave";v="109", "Chromium";v="109"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36' \
  --data-raw '{"childrenBirthdays":[],"departuresCodes":[],"destinationsCodes":[],"durationFrom":6,"durationTo":8,"numberOfAdults":2,"offerType":"BY_PLANE","site":"wypoczynek/wyniki-wyszukiwania-samolot?q=%3Aprice%3AbyPlane%3AT%3AdF%3A6%3AdT%3A8%3ActAdult%3A2%3ActChild%3A0%3AtripType%3AWS&fullPrice=false","filters":[{"filterId":"priceSelector","selectedValues":[]},{"filterId":"board","selectedValues":[]},{"filterId":"amountRange","selectedValues":[]},{"filterId":"minHotelCategory","selectedValues":["defaultHotelCategory"]},{"filterId":"tripAdvisorRating","selectedValues":["defaultTripAdvisorRating"]},{"filterId":"beach_distance","selectedValues":["defaultBeachDistance"]},{"filterId":"facilities","selectedValues":[]},{"filterId":"WIFI","selectedValues":[]},{"filterId":"sport_and_wellness","selectedValues":[]},{"filterId":"room_type","selectedValues":[]},{"filterId":"room_attributes","selectedValues":[]},{"filterId":"hotel_chain","selectedValues":[]},{"filterId":"airport_distance","selectedValues":[]},{"filterId":"flight_category","selectedValues":[]}],"metaData":{"page":1,"pageSize":300,"sorting":"price"}}' \
  --compressed