server:
  port: 1443
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rsww_175651_touroperator
      auto-index-creation: true

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson