version: '3.8'


services:

  broker_axon:
    image: rsww_175651-broker_axon

  svc_gateway:
    image: rsww_175651-svc_gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "17565:17565"
    #      - "1438:1438"
    networks:
      - net_postgres
      - net_mongo
      - net_internal

  svc_hotel:
    image: rsww_175651-svc_hotel
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    ports:
    #      - "1439:1439"
    networks:
      - net_postgres
      - net_mongo
      - net_internal

  svc_flight:
    image: rsww_175651-svc_flight
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    ports:
    #      - "1440:1440"
    networks:
      - net_postgres
      - net_mongo
      - net_internal

  svc_payment:
    image: rsww_175651-svc_payment
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    ports:
    #      - "1441:1441"
    networks:
      - net_postgres
      - net_mongo
      - net_internal

  svc_saga_orchestrator:
    image: rsww_175651-svc_saga_orchestrator
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    ports:
    #      - "1442:1442"
    networks:
      - net_postgres
      - net_mongo
      - net_internal

  svc_tour_operator_cmd:
    image: rsww_175651-svc_tour_operator_cmd
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    ports:
    #      - "1443:1443"
    networks:
      - net_postgres
      - net_mongo
      - net_internal

  svc_tour_operator_query:
    image: rsww_175651-svc_tour_operator_query
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    ports:
    #      - "1444:1444"
    networks:
      - net_postgres
      - net_mongo
      - net_internal

  svc_travel_agency:
    image: rsww_175651-svc_travel_agency
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    ports:
    #      - "1445:1445"
    networks:
      - net_postgres
      - net_mongo
      - net_internal

networks:
  net_mongo:
    external: true
    name: admin-mongodb_default
  net_postgres:
    external: true
    name: admin-postgres_default
  net_internal:
