version: '2.1'


services:
  rswwtest_postgres:
    build: ./ctx-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  rswwtest_mongo:
    build: ./ctx-mongodb
    ports:
      - "27017:27017"

  rswwtest_axon:
    build: ./ctx-axonserver
    ports:
      - "8024:8024"
      - "8124:8124"

  pgadmin:
    container_name: pgadmin_client
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  rswwtest_mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=rswwtest_mongo