version: '2.1'


services:

  rsww_175651_frontend:
    build:
      context: ../frontend
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ../frontend:/project
      - /project/node_modules

  rsww_175651_postgres:
    build: ./ctx-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=svc_client
    volumes:
      - rsww_175651_vol_postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 10s
      retries: 5

  rsww_175651_mongodb:
    build: ./ctx-mongodb
    ports:
      - 27017:27017
    volumes:
      - rsww_175651_vol_mongo:/data/db

  rsww_175651_pgadmin:
    build: ./ctx-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:5050"

  rsww_175651_svc_gateway:
    build: ./ctx-svc-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "1438:1438"
    depends_on:
      rsww_175651_postgres:
        condition: service_healthy

  rsww_175651_svc_hotel:
    build: ./ctx-svc-hotel
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "1439:1439"

  rsww_175651_svc_flight:
    build: ./ctx-svc-flight
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "1440:1440"

  rsww_175651_svc_payment:
    build: ./ctx-svc-payment
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "1441:1441"

  rsww_175651_svc_saga_orchestrator:
    build: ./ctx-svc-saga-orchestrator
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "1442:1442"

  rsww_175651_svc_tour_operator_cmd:
    build: ./ctx-svc-tour-operator-cmd
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "1443:1443"

  rsww_175651_svc_tour_operator_query:
    build: ./ctx-svc-tour-operator-query
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "1444:1444"

  rsww_175651_svc_travel_agency:
    build: ./ctx-svc-travel-agency
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "1445:1445"

volumes:
  rsww_175651_vol_mongo:
  rsww_175651_vol_postgres:
