version: '2.1'


services:

  rproxy:
    build: ./ctx-nginx
    ports:
      - "8088:8088"
    depends_on:
      - frontend
      - svcgateway
    networks:
      - net_internal

  rsww_postgres:
    build: ./ctx-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - net_internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 10s
      retries: 5

  rsww_mongo:
    build: ./ctx-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=student
      - MONGO_INITDB_DATABASE=rsww175651
    ports:
      - "27017:27017"
    networks:
      - net_internal

  axonserver:
    build: ./ctx-axonserver
    hostname: axonserver
    networks:
      - net_internal

  frontend:
    build: ../frontend
    environment:
      - RSWW_BACKEND_ADDR=http://localhost:1438
    networks:
      - net_internal
    ports:
      - "4200:4200"

  svcgateway:
    build: ./ctx-svc-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PSQL_ADDR=rsww_postgres
      - MONGO_ADDR=rsww_mongo
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "1438:1438"
    networks:
      - net_internal
    depends_on:
      rsww_postgres:
        condition: service_healthy

  svchotel:
    build: ./ctx-svc-hotel
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PSQL_ADDR=rsww_postgres
      - MONGO_ADDR=rsww_mongo
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "1439:1439"
    networks:
      - net_internal

  svcflight:
    build: ./ctx-svc-flight
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PSQL_ADDR=rsww_postgres
      - MONGO_ADDR=rsww_mongo
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "1440:1440"
    networks:
      - net_internal
    depends_on:
      rsww_postgres:
        condition: service_healthy

  svcpayment:
    build: ./ctx-svc-payment
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PSQL_ADDR=rsww_postgres
      - MONGO_ADDR=rsww_mongo
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "1441:1441"
    networks:
      - net_internal
    depends_on:
      rsww_postgres:
        condition: service_healthy

  svcsagaorchestrator:
    build: ./ctx-svc-saga-orchestrator
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PSQL_ADDR=rsww_postgres
      - MONGO_ADDR=rsww_mongo
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "1442:1442"
    networks:
      - net_internal
    depends_on:
      rsww_postgres:
        condition: service_healthy

  svctouroperatorcmd:
    build: ./ctx-svc-tour-operator-cmd
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PSQL_ADDR=rsww_postgres
      - MONGO_ADDR=rsww_mongo
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "1443:1443"
    networks:
      - net_internal
    depends_on:
      rsww_postgres:
        condition: service_healthy

  svctouroperatorquery:
    build: ./ctx-svc-tour-operator-query
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PSQL_ADDR=rsww_postgres
      - MONGO_ADDR=rsww_mongo
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "1444:1444"
    networks:
      - net_internal
    depends_on:
      rsww_postgres:
        condition: service_healthy

  svctravelagency:
    build: ./ctx-svc-travel-agency
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PSQL_ADDR=rsww_postgres
      - MONGO_ADDR=rsww_mongo
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "1445:1445"
    networks:
      - net_internal
    depends_on:
      rsww_postgres:
        condition: service_healthy

networks:
  net_internal:
    name: rsww_175651_net
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/16"
          gateway: "10.10.0.1"
