version: '3.8'


services:

  rproxy:
    image: localhost:5000/rsww_175651-rproxy
    ports:
      - "17565:8088"
    networks:
      - net_internal

  axonserver:
    image: localhost:5000/rsww_175651-axonserver
    networks:
      - net_internal
      - net_postgres
      - net_mongo

  frontend:
    image: localhost:5000/rsww_175651-frontend
    environment:
      - RSWW_BACKEND_ADDR=routed
    networks:
      - net_internal
      - net_postgres
      - net_mongo

  svcgateway:
    image: localhost:5000/rsww_175651-svcgateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RSWW_AXONSERVERS=axonserver
    ports:
      - "17565:1438"

  svchotel:
    image: localhost:5000/rsww_175651-svchotel
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RSWW_AXONSERVERS=axonserver

  svcflight:
    image: localhost:5000/rsww_175651-svcflight
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RSWW_AXONSERVERS=axonserver

  svcpayment:
    image: localhost:5000/rsww_175651-svcpayment
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RSWW_AXONSERVERS=axonserver

  svcsagaorchestrator:
    image: localhost:5000/rsww_175651-svcsagaorchestrator
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RSWW_AXONSERVERS=axonserver

  svctouroperatorcmd:
    image: localhost:5000/rsww_175651-svctouroperatorcmd
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RSWW_AXONSERVERS=axonserver

  svctouroperatorquery:
    image: localhost:5000/rsww_175651-svctouroperatorquery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RSWW_AXONSERVERS=axonserver

  svctravelagency:
    image: localhost:5000/rsww_175651-svctravelagency
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - RSWW_AXONSERVERS=axonserver


networks:
  net_mongo:
    external: true
    name: admin-mongodb_default
  net_postgres:
    external: true
    name: admin-postgres_default
  net_internal:
    driver: overlay
    name: rsww_175651_net
    ipam:
      driver: default
      config:
        - subnet: "10.10.0.0/16"
          gateway: "10.10.0.1"

