
spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  data:
#    mongo:
#      repositories:
#        enabled: false
    mongodb:
      uri: mongodb://localhost:27017/hoteldb
server:
  port: 1439


axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson