
spring:
  data:
    mongo:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PWD:student}@${MONGO_ADDR:admin-mongodb_mongo}:${MONGO_PORT:27017}/rsww_175651_svc_hotel?serverSelectionTimeoutMS=15000&connectTimeoutMS=15000

axon:
  axonserver:
    servers: ${AXON_ADDR:broker_axon}:${AXON_PORT:8124}