
spring:
  rabbitmq:
    host: yetirswwrmq
    port: 5672
    username: testuser
    password: testpassword
  data:
    mongo:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://rsww_175651_mongodb:27017/rsww_175651_hotel?serverSelectionTimeoutMS=15000&connectTimeoutMS=15000