server:
  port: 1445
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rsww_175651_travelagency
      auto-index-creation: true

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson