server:
  port: 1445

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/svc_travel_agency
    username: rsww175651
    password: jpg4ever
  jpa:
    hibernate:
      ddl-auto: update


axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson