
CREATE USER rsww175651 WITH PASSWORD 'jpg4ever';

CREATE DATABASE svc_client;
GRANT ALL PRIVILEGES ON DATABASE svc_client TO rsww175651;

CREATE DATABASE svc_flight;
GRANT ALL PRIVILEGES ON DATABASE svc_flight TO rsww175651;