
CREATE USER rsww175651 WITH PASSWORD 'jpg4ever';

CREATE DATABASE svc_client;
GRANT ALL PRIVILEGES ON DATABASE svc_client TO rsww175651;
ALTER DATABASE svc_client OWNER TO rsww175651;

CREATE DATABASE svc_flight;
GRANT ALL PRIVILEGES ON DATABASE svc_flight TO rsww175651;
ALTER DATABASE svc_flight OWNER TO rsww175651;

CREATE DATABASE svc_gateway;
GRANT ALL PRIVILEGES ON DATABASE svc_gateway TO rsww175651;
ALTER DATABASE svc_gateway OWNER TO rsww175651;

CREATE DATABASE svc_travel_agency;
GRANT ALL PRIVILEGES ON DATABASE svc_travel_agency TO rsww175651;
ALTER DATABASE svc_travel_agency OWNER TO rsww175651;