version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: rsww_175651_mongodb
    ports:
      - 27017:27017
    volumes:
      - ../volumes/tour_operator_mongodb/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  axonserver:
    image: axoniq/axonserver
    container_name: axonserver
    ports:
      - 8024:8024
      - 8124:8124
    environment:
      - AXONSERVER_HOSTNAME=axonserver

networks:
  default:
    name: mongodb_network