
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongo:
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://localhost:27017/testdb
server:
  port: 1439