server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/svc_client
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update