server:
  port: 1438

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rsww_175651_svc_gateway
    username: postgres
    password: student
  jpa:
    hibernate:
      ddl-auto: update

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson