server:
  port: 1438

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rsww_175651_svc_gateway
    username: rsww175651
    password: jpg4ever
  jpa:
    hibernate:
      ddl-auto: update

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    servers: 192.168.0.75:8124