
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8089