
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/svc_client
    username: postgres
    password: password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#hibernate:
#  temp:
#    use_jdbc_metadata_defaults: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8089