server:
  port: 1444
spring:
  data:
    mongodb:
      uri: mongodb://root:student@localhost:27017/rsww_175651_touroperator?serverSelectionTimeoutMS=15000&connectTimeoutMS=15000&authSource=admin
      auto-index-creation: true


axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson