spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://${MONGO_USER:root}:${MONGO_PWD:student}@${MONGO_ADDR:admin-mongodb_mongo}:${MONGO_PORT:27017}/rsww_175651_to_query_agency?serverSelectionTimeoutMS=15000&connectTimeoutMS=15000&authSource=admin

axon:
  axonserver:
    servers: ${RSWW_AXONSERVERS:axonserver}