spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PWD:student}@${MONGO_ADDR:admin-mongodb_mongo}:${MONGO_PORT:27017}/rsww_175651_touroperator?serverSelectionTimeoutMS=15000&connectTimeoutMS=15000

axon:
  axonserver:
    servers: broker_axon:8124